import moment from 'moment'


const wa001 = {
  course_label: "WA-001",
  path: "wa001",
  id: "wa001",
  title: "Create your own Web Application",
  description: "This is a series of lessons to introduce you to creating your own web application on the public web.",
  topics: [
    {
      topic_label: "1",
      id: "wa001_t1",
      title: "Introduction",
      lessons: [
        {
          lesson_label: "1",
          path: "001",
          id: "wa001_001",
          title: "#1: Learn to create your own web applications",
          description: "Learn how to create your own web applications on the public web. Introduces technologies including React, Material Design, mui.com, Next.js, static site deployments, Google Firebase hosting, Firebase authentication, and Firebase database synchronization.",
          published: moment("2022-02-19"),
          duration: moment.duration("0:9:28"),
          youTubeCode: "y6K86BbPYjk",
        },
      ]
    },
    {
      topic_label: "2",
      id: "wa001_t2",
      title: "Website Basics",
      lessons: [
        {
          lesson_label: "2",
          path: "002",
          id: "wa001_002",
          title: "#2: Introduction to web hosting",
          description: "An introduction to options for hosting websites, touching on topics such as choosing between SaaS  content management solutions like wix.com and Squarespace versus open source like WordPress and Joomla. Also touches on topics such as domain name management.",
          published: moment("2022-02-19"),
          duration: moment.duration("0:05:44"),
          youTubeCode: "lzwG93ITzF4",
        },
        {
          lesson_label: "3",
          path: "003",
          id: "wa001_003",
          title: "#3: Installing Next.js",
          description: "Next.js is a set of tools to simplify building web apps using React. This lesson talks about installing Node.js (the JavaScript runtime environment), Next.js (a framework for building web applications), and basic tools to get started.",
          published: moment("2022-02-19"),
          duration: moment.duration("0:09:20"),
          youTubeCode: "pRJO2YBmdQk",
        },
        {
          lesson_label: "4",
          path: "004",
          id: "wa001_004",
          title: "#4: Installing the MUI Material UI Library",
          description: "Material UI is a look-and-feel for user interfaces, defined by Google. MUI.com defines a set of React components that can be used with Next.js to create web applications. This library takes away much of the need to learn HTML and CSS in depth. There is also a library of almost 2,000 icons defined by Material.",
          published: moment("2022-02-19"),
          duration: moment.duration("0:06:48"),
          youTubeCode: "qWM1kCQXaA8",
        },
        {
          lesson_label: "5",
          path: "005",
          id: "wa001_005",
          title: "#5: Set up Firebase hosting for your site static files",
          description: "Learn how to set up Google Firebase for hosting static files (created by Next.js) on a public web site. This is where we take the web app we were building locally and make it available on the public web. Google Firebase hosting provides cheap hosting of static files (free for small volumes of downloads).",
          published: moment("2022-02-19"),
          duration: moment.duration("0:03:54"),
          youTubeCode: "so-RD-SGE20",
        },
        /* NOT PUBLISHED YET! INSERTED AFTER 7 WAS RECORDED.
        {
          lesson_label: "6",
          path: "006",
          id: "wa001_006",
          title: "#6: Run a local copy of the LMS web app",
          description: "Download and run the Learning Management System (LMS) app so can experiment with local changes before going full on into developing your own site.",
          published: moment("2022-02-19"),
          duration: moment.duration("0:10:00"),
          youTubeCode: "TODO",
        },
        */
      ]
    },
    {
      topic_label: "2",
      id: "wa001_t2",
      title: "Publishing",
      lessons: [
        {
          lesson_label: "7",
          path: "007",
          id: "wa001_007",
          title: "#7: Introduction to HTML",
          description: "Learn the basics of HTML markup (open and close tags, attributes), and the main differences to XML (which is used by React). Also spends some time on how to embed structured data into HTML pages, to help search engines correctly understand the purpose of your page, and how to use Chrome Developers Tools to examine the HTML on a page, which can be useful later to diagnose problems on HTML pages.",
          published: moment("2022-02-19"),
          duration: moment.duration("0:17:28"),
          youTubeCode: "69NWbfYXmBo",
        },
        /*{
          lesson_label: "8",
          path: "008",
          id: "wa001_008",
          title: "#8: ...",
          description: "...",
          published: moment("2018-10-21"),
          duration: moment.duration("0:18:35"),
          youTubeCode: "9OTnDtsVk6U",
        },*/
      ]
    },
    /*{
      topic_label: "3",
      id: "wa001_t3",
      title: "Movement",
      lessons: [
        {
          lesson_label: "1",
          path: "009",
          id: "wa001_009",
          title: "#9: ...",
          description: "Tutorial on moving puppets in a straight line within an Adobe Character Animator project. See also episode 8 for more examples. This tutorial includes moving a puppet in a straight line using 'blends'. It also includes moving the background using a blend for a camera pan effect.",
          published: moment("2018-10-21"),
          duration: moment.duration("0:14:07"),
          youTubeCode: "BUbbU6g8g10",
        },
        {
          lesson_label: "2",
          path: "010",
          id: "wa001_010",
          title: "#10: ...",
          description: "Tutorial on how to make a copy of a puppet so you can try editing it without messing up the original puppet within an Adobe Character Animator project. There are two ways: 'Duplicate' within a project that duplicates the rigging but not the artwork, and doing a puppet export then import.",
          published: moment("2018-10-21"),
          duration: moment.duration("0:8:57"),
          youTubeCode: "SPNFlQwb13o",
        },
        {
          lesson_label: "3",
          path: "011",
          id: "wa001_011",
          title: "#11: ...",
          description: "Tutorial on how to make a puppet look like its walking in Adobe Character Animator without using the Walk Behavior. This uses a combination of linear blends (see Episode 9) and short Y blends to make the character bob up and down. It also demonstrates using scale blends on the background.",
          published: moment("2018-10-21"),
          duration: moment.duration("0:11:42"),
          youTubeCode: "ra-tuYYTzXM",
        },
        {
          lesson_label: "4",
          path: "012",
          id: "wa001_012",
          title: "Episode 12: Floating Puppet Movement",
          description: "Tutorial on how to move a puppet as if it is floating within an Adobe Character Animator project. To do this, I find it easiest to make a copy of a puppet (described in episode 10) then remove the pins from the feet and use a dragger to move the puppet around the scene. In this tutorial we show a wookie floating away with a balloon, but also a butterfly flapping around the screen.",
          published: moment("2018-10-21"),
          duration: moment.duration("0:13:13"),
          youTubeCode: "yLvp6-e-7ko",
        },
        {
          lesson_label: "5",
          path: "013",
          id: "wa001_013",
          title: "Episode 13: Wind Blowing Balloon",
          description: "In episode 12 we showed how to make the Wookie float away carried by a balloon. This episode we add some wind and physics behaviors to the balloon to give it a bit more life!",
          published: moment("2018-10-21"),
          duration: moment.duration("0:8:56"),
          youTubeCode: "AMdXQ9amZAM",
        },
        {
          lesson_label: "6",
          path: "014",
          id: "wa001_014",
          title: "Episode 14: Holding and Releasing Balloon",
          description: "In this episode we show how the Wookie can hold and then release the Balloon. This is using a new feature called Magnets. Magnets unfortunately don't work with Dangles, so if you add a dangle the magnet stops working. (Next episode I show how to get them both working together.) NOTE: I had in the Magnet behavior the attach property set to HINGE which made the balloon sway backwards and forwards. Using WELD stopped that, but had the string act like a hard stick, which eliminated the sway.",
          published: moment("2018-10-21"),
          duration: moment.duration("0:17:33"),
          youTubeCode: "8BSxR9HWzI4",
        },
        {
          lesson_label: "7",
          path: "015",
          id: "wa001_015",
          title: "Episode 15: Releasing Balloon on a Windy Day",
          description: "Episode 14 demonstrated releasing a balloon, but it did not sway in the wind. This episode combines a few techniques for the ultimate release of a balloon on a windy day. (This is no longer what I would call 'beginner' but it rounds out the last few episodes nicely.)",
          published: moment("2018-10-21"),
          duration: moment.duration("0:13:29"),
          youTubeCode: "ciyZbykwH4k",
        },
      ]
    },
    {
      topic_label: "4",
      id: "wa001_t4",
      title: "Eyes and Mouth",
      lessons: [
        {
          lesson_label: "1",
          path: "016",
          id: "wa001_016",
          title: "Episode 16: Adding Eyebrows",
          description: "The balloon has blown away - time to get back to adding some more details to our basic puppet. In this episode we add some simple eyebrows to the puppet. We look at two approaches - use handles to warp the face, and using an independent layer to hold the eyebrows (my preference).",
          published: moment("2018-10-22"),
          duration: moment.duration("0:16:13"),
          youTubeCode: "1I_sQR_YRqk",
        },
        {
          lesson_label: "2",
          path: "017",
          id: "wa001_017",
          title: "Episode 17: Quick Eyes and Mouth",
          description: "In this episode we are going to steal eyes and mouth from another Adobe Character Animator puppet and add them to our Wookie. This can be a useful way to get something going quickly. You can then go back and refine them later.",
          published: moment("2018-10-23"),
          duration: moment.duration("0:21:57"),
          youTubeCode: "g0v-iDYEgkY",
        },
        {
          lesson_label: "3",
          path: "018",
          id: "wa001_018",
          title: "Episode 18: Eye Pupil Movements",
          description: "In this episode we try a few different ways of making the eyes look more consistent with the rest of the puppet. The eyes are one of the most tricky areas to get right in Adobe Character Animator puppets, but they are also one of the most important features of puppets as that is where we focus our attention - we look other people in the eyes.",
          published: moment("2018-10-25"),
          duration: moment.duration("0:32:09"),
          youTubeCode: "lQuvKdAgSG4",
        },
        {
          lesson_label: "4",
          path: "019",
          id: "wa001_019",
          title: "Episode 19: Eye Blinks",
          description: "In this episode we look at eye blinking - using the webcam and using the Auto Blink behavior (which I like).",
          published: moment("2018-10-25"),
          duration: moment.duration("0:7:50"),
          youTubeCode: "hP_Ok4UCaRo",
        },
        {
          lesson_label: "5",
          path: "020",
          id: "wa001_020",
          title: "Episode 20: Recording Eye Movements",
          description: "In this episode we look at recording eye movements, then going back and editing the eye positions and how to merge the results nicely together. (Re-recorded.) [Sorry for the poor sound quality - not sure why different to previous episodes!]",
          published: moment("2018-10-25"),
          duration: moment.duration("0:23:00"),
          youTubeCode: "iDOKY4iLaks",
        },
        {
          lesson_label: "6",
          path: "021",
          id: "wa001_021",
          title: "Episode 21: Crazy Eyes",
          description: "In this episode we look at fixing crazy eyes (short).",
          published: moment("2018-10-25"),
          duration: moment.duration("0:6:45"),
          youTubeCode: "sNYJ3-aB0Sw",
        },
        {
          lesson_label: "7",
          path: "022",
          id: "wa001_022",
          title: "Episode 22: Basic Oral Hygiene (Mouths)",
          description: "Mouths are important for talking! Make sure your mouth is clean! In this episode I run through the basics of mouths in Adobe Character Animator, introducing visemes, then showing how to add additional expressions (like sad and angry) via triggers, including keyboard triggers for standard visemes like smile and Oh sounds.",
          published: moment("2018-10-26"),
          duration: moment.duration("0:21:24"),
          youTubeCode: "gJFCUw68njA",
        },
      ]
    },
    {
      topic_label: "5",
      id: "wa001_t5",
      title: "Advanced Topics",
      lessons: [
        {
          lesson_label: "1",
          path: "023",
          id: "wa001_023",
          title: "Episode 23: Planning the Audio",
          description: "This episode discusses some options for how to plan the audio (voice actors, music, etc) for you animation. Do you record like a radio show and then animation? Or record short audio clips and move them around in the scene based on animation? Both work - you just need to pick. [Sorry for the below average sound quality!]",
          published: moment("2018-10-28"),
          duration: moment.duration("0:17:50"),
          youTubeCode: "sgoP60Csr68",
        },
        {
          lesson_label: "2",
          path: "024",
          id: "wa001_024",
          title: "Episode 24: Morphing into Super Wookie!",
          description: "It's a bird! It's a plane! No, its Super Wookie! In this episode he reveals how he morphs his clothes from mind mannered Wookie into Super Wookie! We talk about a few ways this can be done in Adobe Character Animator. Contains a bit of Photoshop to create the clothes etc as well. [Sorry for the poor audio quality.]",
          published: moment("2018-10-28"),
          duration: moment.duration("0:23:43"),
          youTubeCode: "PWhClNuxkZI",
        },
        {
          lesson_label: "3",
          path: "025",
          id: "wa001_025",
          title: "Episode 25: Arms for Independence",
          description: "Not a revolutionary war, but rather chopping the arms off the puppet and attachment them as independent layers so get arms going in front of the body correctly. A bit of Photoshop in here to adjust the Photoshop file. Shows independent layers and attaching the arms to the body - more common with Illustrator files. [Sorry, the last few video audio is TERRIBLE! I need to track down the source.]",
          published: moment("2018-10-28"),
          duration: moment.duration("0:30:33"),
          youTubeCode: "DuOvQJTQ9FU",
        },
        {
          lesson_label: "4",
          path: "026",
          id: "wa001_026",
          title: "Episode 26: Repeating Movements",
          description: "In this tutorial we look at how to repeat the same gestures easily. This can make recording a scene faster if the puppet repeats the same actions frequently, but can also be used with a MIDI device to make live streaming simpler (especially if using foot pedals)",
          published: moment("2018-11-02"),
          duration: moment.duration("0:20:17"),
          youTubeCode: "Z3P1X7W85pA",
        },
        {
          lesson_label: "5",
          path: "027",
          id: "wa001_027",
          title: "Episode 27: Seeking Resolution",
          description: "Resolution of images makes a difference, especially when you zoom in on parts of the puppet. So design your puppet from the beginning so you can zoom into the required part of the puppet with high resolution after the zoom. (I often use 6000px x 6000px)",
          published: moment("2018-11-03"),
          duration: moment.duration("0:12:43"),
          youTubeCode: "pV06wGHZr0E",
        },
      ]
    },
    */
  ]
}

export default wa001
